### ISSUE TITLE
Add preloading of asset manifest in the index.html head

### ISSUE THREAD

**Issue by RuslanZavacky** [RuslanZavacky/ember-cli-ifa#1]
`<link src="/asset-manifest.json" preload>`
- [ ] Don't forget about fingerprinted asset map file

**Comment by pedrokost** [comment]
I gave this a try, but I failed.

I tried adding 
```
<link as="script" href="assetmap.json" rel="preload">
```
But this causes Chrome to make 2 requests, because the `as` type differs from the one loaded with `getJSON`. I haven't been able to find a valid `as` attributes for json. Maybe I missed something!
