### ISSUE TITLE
Default prepend value...

### ISSUE THREAD

**Issue by adc-mhaugen** [RuslanZavacky/ember-cli-ifa#10]
Thanks for creating this addon.  I'm wondering why the default value for **prepend** (in services/asset-map) is a slash?  I'm trying to use this with fingerprinting in test and production, but not in development and what I'm seeing is that asset paths are always resolved with a leading slash in development because there is no asset map (so no override of the prepend value).  Is it possible to configure the default value?

Thanks!

**Comment by RuslanZavacky** [comment]
Hey @adc-mhaugen, can you please check if latest 0.4.0 version solves the issue?

**Comment by RuslanZavacky** [comment]
I suppose everything worked fine :) if there will be an issue with that again, please open a new ticket.

**Comment by adc-mhaugen** [comment]
I'm sorry @RuslanZavacky, I didn't mean to blow you off, I just got busy at work.  Thank for your attention.

**Comment by RuslanZavacky** [comment]
@adc-mhaugen no worries :) 
if you can check if latest updates solved it for you, it would be good :) if not, I'll take a look but will need a bit more info, on how you ember-cli-build looks and also your configuration for fingerprinting :)

**Comment by bartocc** [comment]
@RuslanZavacky I think the problem still exist in 0.5.0. In dev I don't fingerprint and then assetMap.prepend is '/'. In prod, I fingerprint, so prepend is '' in the assetMap.json since no other value is provided in the fingerprint config.

This leads to images working in dev but not in prod

**Comment by RuslanZavacky** [comment]
@bartocc do you have `prepend: '/'` set in the config for prod? Like

```
fingerprint: {
  prepend: '/'
}
```

**Comment by bartocc** [comment]
I've had to add this to make it work in prod indeed. But I feel the default '/' in dev leads to 2 different  behaviours that are confusing

**Comment by RuslanZavacky** [comment]
@bartocc I think it came from the idea, that on prod, you might always need to have a prepend, to be more explicit, as if you don't have `/`, as the default, you might have an issue if your project is placed into a subfolder for example.

**Comment by bartocc** [comment]
Ok. Feel free to close this issue if you believe this is normal behaviour. At least this issue will be here for future googlers
