### ISSUE TITLE
Release the last version on the NPM registry

### ISSUE THREAD

**Issue by AlexisMontagne** [RuslanZavacky/ember-cli-ifa#12]
Hello @RuslanZavacky,

We are using your plugin at @upfluence, the commit https://github.com/RuslanZavacky/ember-cli-ifa/commit/c5e7ef0c7bb71f0d3e040cf2fda5aefad02b6f4b is critical for our build process, can i ask you to push a new version with this commit to the npmjs.com registry?

Thank you for your work 😄

**Comment by RuslanZavacky** [comment]
@AlexisMontagne done :) sorry that I've forgot to push it initially.. also, have you tried it on prod, is it working fine? I had some doubts, that there might be more issues..

**Comment by phndiaye** [comment]
Hello, @RuslanZavacky, 

I am also from @upfluence 😄  and yes we are currently using the fix in production on 2 of our products. It's working like a charm 👍  Thanks a lot !

**Comment by RuslanZavacky** [comment]
Good, thx guys :)
