### ISSUE TITLE
Error: asset-map helper not found

### ISSUE THREAD

**Issue by Hucxley** [RuslanZavacky/ember-cli-ifa#16]
Using same syntax as in your usage example:
 model=e
<img src={{ asset-map (concat "assets/images/" e.photoFilename)}} />

e.photoFilename = "photo.jpg"

How do I access the helper, or write my own?

**Comment by RuslanZavacky** [comment]
Hey @Hucxley, can you give a bit more info about this? What you are trying to achieve? Have you configured your fingerprinting, etc.? 

asset-map helper is accessible in the code, after this addon is added.

**Comment by Hucxley** [comment]
Yep, followed your setup on the readme exactly. The only thing I changed is
adding "images/" to the (concat "assets/..." e.photoFilename) instruction
since I have images in a subfolder by themselves

If I look at the html generated after building, it has e.photoFilename as
the exact string in the model. Basically, it's not accessing the helper to
return the mapped asset. The asset key-value pair is correct in the map,
it's just not going out to get it since the helper isn't working.

I didn't build the service on the readme, though, because I thought that
was intended if you wanted to use it as a more complex service and not
helper. Is that where I've gone wrong?

**Comment by RuslanZavacky** [comment]
@Hucxley you did everything right, show me your fingerprinting configuration, it will give more context. Fingerprinting (and these helpers) only for in most cases for production builds, not local ones.

**Comment by Hucxley** [comment]
In config/environment:
ENV:{ ifa: { enabled: true}, ...


In ember-cli-build:

if(environment == "development"){
    fingerprint : {
        enabled: true,
        generateAssetMap: true,
        fingerprintAssetMap: true
     },...
}

I'm trying to figure this out in development environment since I already
got burned by fingerprinting in a production deployment. So, I'm building a
dev environment and looking at the dist files to see what is happening
locally until I figure out a solution, instead of pushing more broken stuff
into production.

**Comment by RuslanZavacky** [comment]
@Hucxley everything looks legit, can you also verify several things then:

[ ] check `index.html`, find `var __assetMapPlaceholder__` and write here, what's the value
[ ] check your `dist/` folder, find `assetMap.json`, and validate, that it is actually fingerprinted.
[ ] check your network tab, to see if there is a failed (or succeeded) request to get `assetMap.json` (fingerprinted I assume)

**Comment by Hucxley** [comment]
1 - don't know (will report back in a couple of hours when I get home from
the office)
2 - Yes
3 - Assume Yes (static assets are being fingerprinted and loaded correctly,
dynamic are not).

I can send you the URL in an IM, and you can look at the same asset in two
different locations to see what's happening, if you want. One is loaded
from the model, the other is currently hard-coded. The hard-coded link
loads the fingerprinted asset, the dynamic does not.


On May 8, 2017 2:36 PM, "Ruslan Zavacky" <notifications@github.com> wrote:

@Hucxley <https://github.com/Hucxley> everything looks legit, can you also
verify several things then:

[ ] check index.html, find var __assetMapPlaceholder__ and write here,
what's the value
[ ] check your dist/ folder, find assetMap.json, and validate, that it is
actually fingerprinted.
[ ] check your network tab, to see if there is a failed (or succeeded)
request to get assetMap.json (fingerprinted I assume)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/RuslanZavacky/ember-cli-ifa/issues/16#issuecomment-299968375>,
or mute the thread

**Comment by RuslanZavacky** [comment]
@Hucxley send me a message in Ember community slack :)

**Comment by Hucxley** [comment]
added excluded: ["images"] since these are going to be static assets anyway.
