### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by Bajena** [RuslanZavacky/ember-cli-ifa#17]
Hi guys, 
when are you planning to release a new version? Lack of this commit https://github.com/RuslanZavacky/ember-cli-ifa/commit/35f48c0a02b1fc4b7ce2e40807f86fbda73d3302#diff-168726dbe96b3ce427e7fedce31bb0bc in version `v0.4.1` breaks CSS hot reload when `ember-cli-inject-live-reload` is used.

**Comment by RuslanZavacky** [comment]
Hey @Bajena, sorry about that, published a new version - 0.5.0 :)

**Comment by Bajena** [comment]
Thank you sir!
