### ISSUE TITLE
Use the new module API

### ISSUE THREAD

**Issue by zeppelin** [RuslanZavacky/ember-cli-ifa#20]
Ex. `import get from 'ember-metal/get';` -> `import { get } from '@ember/object';`, *once [`ember-cli-shims` 1.2.0](https://github.com/ember-cli/ember-cli-shims/releases) is released.*

**Comment by RuslanZavacky** [comment]
@zeppelin PR is appreciated :) or I'll do it as soon as shims will be available )

**Comment by zeppelin** [comment]
Related: https://github.com/ember-cli/ember-cli-shims/pull/127

**Comment by mydea** [comment]
This should be fixed by #33

**Comment by RuslanZavacky** [comment]
Released as part o 0.7.0, thanks to @mydea :)
