### ISSUE TITLE
Script insertion with contentFor triggers CSP warning

### ISSUE THREAD

**Issue by Fl0rianFischer** [RuslanZavacky/ember-cli-ifa#25]
Hi there,

first of all thanks for this great addon! We're currently trying to set up a Content Security Policy for our Ember CLI app. Since this addon is inserting an inline script in the `contentFor` hook, we're getting a CSP error on page load if we don't allow `'unsafe-inline'` in our `script-src` directive (thus making the whole app vulnerable).

Basically what we would need is the option to hash the script and tell ember-csp about the generated hash in the environment file. This issue is not unique to this addon, quite a few seem to be struggling to find a solution to this.

See:
https://github.com/rwjblue/ember-cli-content-security-policy/issues/67
https://github.com/dfreeman/ember-ace/issues/3
https://github.com/pgrippi/ember-cli-google-analytics/issues/21

**Comment by RuslanZavacky** [comment]
Hey @Fl0rianFischer, thank you for bringing it up :) yea... this one is particularly tricky. I am not yet sure what the best solution would be.

One idea might be, is to create a meta tag, and put JS file name there and load when app loads (eg. default flow, but without script tag)

**Comment by RuslanZavacky** [comment]
Also, @Fl0rianFischer can you please check, if this PR (#26) solves your CSP issue?

**Comment by Fl0rianFischer** [comment]
Hey, yes that solves the issue! Thanks so much for your fast reply!

**Comment by RuslanZavacky** [comment]
@Fl0rianFischer released as [v0.6.0](https://github.com/RuslanZavacky/ember-cli-ifa/releases/tag/v0.6.0) 

Thank you for pointing to this :)
