### ISSUE TITLE
Could not find module `rsvp` imported from `ember-cli-ifa/initializers/asset-map`

### ISSUE THREAD

**Issue by badmacstone** [RuslanZavacky/ember-cli-ifa#30]
After updating Ember to 2.16 I removed `ember-cli-shims` (because it's not longer needed). But after removing that package I'm getting the error above. Any suggestions?

**Comment by RuslanZavacky** [comment]
@badmacstone it actually seems, that `ember-cli-shims` should be removed only after ember 3.0. For now, it is still required in projects.
