### ISSUE TITLE
Makes request with "undefined" when assetMap.json is not generated and ifa is not enabled in config

### ISSUE THREAD

**Issue by k-dauda** [RuslanZavacky/ember-cli-ifa#34]
This line https://github.com/RuslanZavacky/ember-cli-ifa/blob/0744021113a1a4e17fe1f9be14550548a014d46e/addon/initializers/asset-map.js#L21 seems to convert undefined to a string which causes the conditional here https://github.com/RuslanZavacky/ember-cli-ifa/blob/0744021113a1a4e17fe1f9be14550548a014d46e/addon/initializers/asset-map.js#L25 to be truthy.

**Comment by ludalex** [comment]
Having the exact same problem. Both in development and in production.

**Comment by RuslanZavacky** [comment]
@k-dauda, @ludalex can you please check if latest version 0.7.0 solves it for you?

**Comment by ludalex** [comment]
@RuslanZavacky It does! Pushed to production as well. Great job, thank you.

**Comment by k-dauda** [comment]
@ludalex yup v0.7.0 works, thanks.
