### ISSUE TITLE
assetmap file is loaded through a relative path which fails when you land on a nested route

### ISSUE THREAD

**Issue by k-dauda** [RuslanZavacky/ember-cli-ifa#35]
The request for the assetMap searches for the it relatively so loading the assetMap from /parent will load correctly but /parent/child and /parent/child/grandchild would not.

**Comment by HarveyKandola** [comment]
@k-dauda try using the 'prepend' option as follows:

		fingerprint: {
			enabled: true,
			generateAssetMap: true,
			fingerprintAssetMap: true,
			prepend: '/'
		}
