### ISSUE TITLE
Fastboot, ifa, and vedor SRI hashes

### ISSUE THREAD

**Issue by eco3162035** [RuslanZavacky/ember-cli-ifa#36]
Hi there,
I am using a configuration with fastboot, as I understand, this is supported.
I am currently having an issue where ember-cli-ifa will modify the index.html file (as intended), however this is done after ember-cli-sri has already created a hash for it, as a result, my fastboot ember app will not load at all due to tampering of vendor.js.
Aside from manually regenerating the correct hash and manually putting this into index.html, is there a faster way to achieve this?
Thanks for your great work

**Comment by eco3162035** [comment]
Hi there,
After further examination, this issue has nothing to do with fastboot.
I realize I have been brief on the issue, in order to reproduce, create an ember app and enable ember-cli-sri and ember-cli-ifa, configure both. Run the app, and it will load due to modification of vendor.js after a hash has already been generated for it.

**Comment by RuslanZavacky** [comment]
@YoranBrondsema yeap.. as you've described. I suppose to overcome this, you can make assets inline or we might think of fallback to a previous option that we have - separate assets filename to load before app loads.

**Comment by Turbo87** [comment]
this should be resolved by #40 AFAICT
