### ISSUE TITLE
Asset map not being added to index.html

### ISSUE THREAD

**Issue by backspace** [RuslanZavacky/ember-cli-ifa#37]
Hello again! I’ve been trying in [this branch](https://github.com/travis-ci/travis-web/pull/1590) to test out integrating your promising addon into our [PR deployment](https://blog.travis-ci.com/2016-11-28-ember-at-travis#pull-request-deployments-with-ember-cli-deploy) workflow, which will address a long-standing problem where dynamically-sourced images don’t display properly. I’m finding that the `assetMap` file isn’t being included in the `index.html`.

I [changed the dynamically-sourced digit images on the landing page to use the asset map](https://github.com/travis-ci/travis-web/pull/1590/commits/7fc0f2530494a07325cb1bf2bfe2865c781f2d6b), to no avail:

![image](https://user-images.githubusercontent.com/43280/39770048-8ebb1704-52b3-11e8-84fc-d6f84e546715.png)

Here’s what it looks like on the production site, for reference:

![image](https://user-images.githubusercontent.com/43280/39770069-9fdc44cc-52b3-11e8-8543-ba08cbf33962.png)

The PR deployment is [here](https://bd-neo-ifa.test-deployments.travis-ci.org/), in case that’s helpful. If you look at the source for `index.html`, you can see the asset map isn’t loaded. Can you imagine any reason why this would be the case? I’m confused. I suspect there’s some dreadfully obvious thing I’m missing.

I really look forward to being able to use your addon; while I’m aware of the limitation that dynamically-sourced images don’t load properly in PR deployments, I’m continually having to assure people that it’s a known problem when they’re looking at them to check into other changes. Thanks for your work on this!

**Comment by RuslanZavacky** [comment]
Hey, @backspace thank you for detailed Issue :) it helped a lot. Also, I do apologize that I haven't paid enough attention to this project lately.

I've checked out `travis-web` branch that you were working on, and was able to make fingerprinting work :) and I've found a bug in `ember-cli-ifa` - https://github.com/RuslanZavacky/ember-cli-ifa/pull/38

Can you please try out this branch and see if it will work for you?

P.S I had to add `fingerprint.enabled = true;` in `ember-cli-build.js` so it starts to fingerprint + changes from the branch that I've specified.

**Comment by backspace** [comment]
No need to apologise! I know it can be a lot of work to maintain an addon, and you’ve already spent so much time addressing my troubles 😳

Thanks for pointing out that the asset map download is within the vendor file, that explains why I couldn’t find it in `index.html`. (But it wasn’t there even with `inline: true`? 🤔) But I don’t see it being fetched in the developer tools network tab, which I expect should happen? This is true even on your `fix-regex-test-for-vendor` branch.

There are a lot of moving parts here; I’m only testing this via PR deployment because that’s the environment I’m targeting. If I can get it to work as desired, then I’ll add the necessary flags for different handling in other environments.

**Comment by RuslanZavacky** [comment]
@backspace got to a root of this... latest release and assumption to put asset map into vendor.js didn't work well, unfortunately. 

I've attached a git patch with changes that I've used for travis-web to make assets work, but it essentially disables SRI. I don't recommend to use it in prod for now. I will work on the next version of cli-ifa to fallback to our previous approach with index.html placeholders.

[working_without_sri.txt](https://github.com/RuslanZavacky/ember-cli-ifa/files/1991271/working_without_sri.txt)

**Comment by backspace** [comment]
Thanks for the further investigation! I’ve reached the end of my timebox for experimenting with this for now, but I appreciate all your support. I look forward to when I can use this to solve the longstanding dynamic assets problem. 💞

**Comment by RVenkatesh** [comment]
Any updates on this? Because for me since assetMap-{#hash}.json is loaded from inside vendor.js, whenever there is no change in vendor.js, the cached version of it will be loaded in the browser, which in turn will try to load the old assetMap-{#hash}.json file.

**Comment by Turbo87** [comment]
resolved by #40 AFAICT
