### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by denzo** [RuslanZavacky/ember-cli-ifa#4]
Does this need to be inserted manually? and if so how does the `hash` get in the index.html?
```
<script>var __assetMapFilename__ = "/blog/assets/assetMap-<hash>.json";</script>
```

**Comment by denzo** [comment]
Oh I see. Removing  `-<hash>` does the job.

**Comment by denzo** [comment]
However, in `development` the assetMap is not generated and thus I get `404` from the inserted script inside index.html.

Confused.

**Comment by RuslanZavacky** [comment]
Hey @denzo this shouldn't be the case. You don't need to modify anything. Can you show me your environment.js?

It might be a bug, but need to identify, whats causing it :)

**Comment by denzo** [comment]
I actually have nothing in the `environment.js`. However, I did have to add the following to the `ember-cli-build.js`

```
fingerprint: {
  generateAssetMap: true,
  fingerprintAssetMap: true
},
```

I also noticed that `prepend` is taken from the loaded `assetMap.json`. But I can't figure out how to set it in there.

**Comment by denzo** [comment]
Apologies, you are right it was inserted automatically. I'm not sure what happened.

But do I still have to amend `ember-cli-build.js` file?

**Comment by RuslanZavacky** [comment]
Have you addrd in your config env:

’’’
ifa: {
  enabled: true
}
’’’
?

**Comment by RuslanZavacky** [comment]
Also, I've confused you a bit, you need to add in index.html assetmap file variable, as shown in README in section for apps in sub-folders (if your app is in sub-folder) ;)

**Comment by denzo** [comment]
Ok, here's what's happening. `ifa.enabled` is true by default. Therefore when run in development I get 404 trying to load the assetMap.json as it is inserted.

https://github.com/RuslanZavacky/ember-cli-ifa/blob/master/index.js#L50

**Comment by RuslanZavacky** [comment]
@denzo where you see that it is enabled: true by default? you mean its enabled in your config by default?

**Comment by denzo** [comment]
Here, I've created a fresh Ember project and installed `ember-cli-ifa` and added a login route. No changes to the `config/environment.js` has been made. Try running it in development `ember s`.

https://github.com/denzo/ifa-test

Notice that `<script>var __assetMapFilename__ = "__asset_map_placeholder__";</script>` is inserted into the `index.html` and thus causes **404**.

**Comment by RuslanZavacky** [comment]
Thank you @denzo I've found some issues, and when started to fix them, more issues appear :) you are right, that this addon is actually enabled by default and it is a bit unexpected behavior.

**Comment by denzo** [comment]
Also, it doesn't work without adding the below to `ember-cli-build.js`
```
fingerprint: {
      generateAssetMap: true,
      fingerprintAssetMap: true,
      prepend: '/'
    },
```

**Comment by RuslanZavacky** [comment]
Thank you @denzo for your input! I will improve documentation to clarify better configuration process and last PR will fix initial confusion :)
