### ISSUE TITLE
vendor.js file MD5 checksum

### ISSUE THREAD

**Issue by griZZZly8** [RuslanZavacky/ember-cli-ifa#50]
`  ifa: {
    enabled: true,
    inline: true
  }`

IFA injects asset map into vendor.js on postBuild hook, looks like checksum calculated before this step.  As result I can get same filename but content of files is different. This is kind of problem for cloudfront for example. Any ideas?

**Comment by Turbo87** [comment]
this should be fixed by #40 AFAIK
