### ISSUE TITLE
can master branch be released as 0.8.0 ?

### ISSUE THREAD

**Issue by BnitoBzh** [RuslanZavacky/ember-cli-ifa#52]
because jquery was removed in favor of fetch ... no deps to ember-ajax or jquery ...

**Comment by BnitoBzh** [comment]
and with pending pull requests

**Comment by mansona** [comment]
@Turbo87 I guess this can be closed now that the release was cut? 🎉

**Comment by Turbo87** [comment]
yeah, thanks :)
