### ISSUE TITLE
Use dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by Turbo87** [RuslanZavacky/ember-cli-ifa#63]
It would be great to use a service like https://dependabot.com/ to keep the dependencies of this project up-to-date. Unfortunately only @RuslanZavacky will be able to enable it since it's not part of a GitHub org.

@RuslanZavacky could you go to https://github.com/apps/dependabot-preview/installations/new and give it access to this repo? the rest can probably be handled with a config file in the repo. 🙏 

alternatively, we could also move the project into the https://github.com/adopted-ember-addons org.

**Comment by RuslanZavacky** [comment]
@Turbo87 done 👍

**Comment by RuslanZavacky** [comment]
Btw, I am also fine to move it under adopted umbrella :)

**Comment by Turbo87** [comment]
>  I am also fine to move it under adopted umbrella :)

sweet. the process would be that you transfer the repo to @melsumner, she will move it into the org and then give you all the necessary permissions there :)

**Comment by RuslanZavacky** [comment]
Sent request to @MelSumner for transfer :)
