### ISSUE TITLE
Lazy load asset map?

### ISSUE THREAD

**Issue by ryanto** [RuslanZavacky/ember-cli-ifa#9]
Wanted to get your thoughts on lazy loading the asset map when the service is first used, rather than using an initializer that defers readiness.

This would break the current API: `resolve` https://github.com/RuslanZavacky/ember-cli-ifa/blob/master/addon/services/asset-map.js#L8 would return a promise instead of a string.

I can spike on this if this is something that interests you.

**Comment by RuslanZavacky** [comment]
@ryanto that's a good idea, but I am a bit not sure what kind of changes you want to propose in asset-map.js file, for `resolve` method? This service already operates with passed in data. Or you think of passing map property as a promise, and resolve in the method? This might be an interesting challenge, to make it correctly, as if assets are loading, as images, for example, you have to handle them specifically in the code, to avoid having 'missing' images for some moment.

Maybe if we introduce an option, eg. async/sync mode, it might work for both cases.
